### ISSUE TITLE
// onPan callback does not work

### ISSUE THREAD

**Issue by taskibayev** [avcs06/SVGPanZoom#1]
hi
i like your lib. It's very convinient for my little project.

so issue is that 
`// onPan callback, coordinates = {x: x, y: y}
        callback: Function (function(coordinates) {})
`
does not fires (does not work) in my app. 

can you give some help.

thank you

**Comment by taskibayev** [comment]
well actually it's works when i use panLeft() method
It would be pretty nice if could fire this function on drag event

**Comment by taskibayev** [comment]
actually i solved in my own way. 
Here is   [solution]https://github.com/lab362/SVGPanZoom/commit/fbe2de58edfa7f0cbcb427e440b9f2c0dc78a24b)

**Comment by avcs06** [comment]
Hey it is still in development phase. Thank you for your interest, now i have to complete this faster :)

**Comment by avcs06** [comment]
You can send pull request, if you want to contribute
